# Generated by Django 4.2.7 on 2023-11-18 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('cite', models.CharField(default='', max_length=100)),
                ('zipcode', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'adress',
            },
        ),
        migrations.CreateModel(
            name='contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=50)),
                ('familyName', models.CharField(max_length=50)),
                ('birthDate', models.DateField(default=datetime.date(2004, 1, 1))),
                ('email', models.EmailField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date(2004, 1, 1))),
                ('time', models.TimeField()),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['name', 'date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('familyName', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date(2004, 1, 1))),
                ('description', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('adresse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.adress')),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('nbr', models.FloatField()),
                ('date', models.DateField(default=datetime.date(2004, 1, 1))),
                ('type', models.CharField(choices=[('VIP', 'Very important Person'), ('S', 'Simple...')], max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('loc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.location')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('contributor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.contributor')),
                ('level', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('adrr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.adress')),
            ],
            options={
                'db_table': 'participant',
            },
            bases=('app.contributor',),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('barCide', models.CharField(blank=True, max_length=300, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.reservation')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('event_org', models.ManyToManyField(to='app.event')),
            ],
            options={
                'db_table': 'Organizer',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location'),
        ),
        migrations.CreateModel(
            name='animation',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('birthDate', models.DateField(default=datetime.date(2004, 1, 1))),
                ('level', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('a', models.ManyToManyField(to='app.event')),
            ],
            options={
                'db_table': 'animation',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='part_event_reserv',
            field=models.ManyToManyField(through='app.Reservation', to='app.event'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'date', 'time')},
        ),
        migrations.CreateModel(
            name='Animator',
            fields=[
                ('contributor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.contributor')),
                ('phone', models.CharField(max_length=30)),
                ('animator_event', models.ManyToManyField(to='app.event')),
            ],
            options={
                'db_table': 'Animator',
            },
            bases=('app.contributor',),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('participant', 'event')},
        ),
    ]
